name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  application_name: Application
  updater_name: Updater
  build_config: Release

jobs:
  update_version_in_source:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    # prepare version update
    - name: extract tag
      uses: olegtarasov/get-tag@v2.1
      id: tagName
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # update versions locally
    - name: update application version
      run: python buildscripts/update_version.py --tagname ${{ steps.tagName.outputs.tag }} --project-file ${{ env.application_name }}/${{ env.application_name }}.csproj
    - name: update updater version
      run: python buildscripts/update_version.py --tagname ${{ steps.tagName.outputs.tag }} --project-file ${{ env.updater_name }}/${{ env.updater_name }}.csproj
    - name: push updated version number
      uses: test-room-7/action-update-file@v1
      with:
          file-path: |
              ${{ env.application_name }}/${{ env.application_name }}.csproj
              ${{ env.updater_name }}/${{ env.updater_name }}.csproj
          commit-msg: Update version number
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
    # create empty release
    - name: create empty release
      uses: softprops/action-gh-release@v1

  
  create-release:
    needs: update_version_in_source
    runs-on: windows-latest
    strategy: 
      matrix:
        include: 
        - name: windows
          asset_identifier: "-Windows"
          RID: win-x64
        - name: Linux
          asset_identifier: "Linux"
          RID: linux-x64
        - name: Mac
          asset_identifier: "Mac"
          RID: osx-x64
    steps:
      # checkout
      - name: checkout
        uses: actions/checkout@v2
      # extract tag
      - name: extract tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
      # setup runtime
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
    
      # publish program to {application_name}/{os_name}
      - name: publish program ${{ matrix.name }}
        run: dotnet publish ${{ env.application_name }} --configuration ${{ env.build_config }} -r ${{ matrix.RID }} --no-self-contained -o ${{ env.application_name }}/${{ matrix.name }}
      # publish updater to {application_name}/{os_name}
      - name: publish updater ${{ matrix.name }}
        run: dotnet publish ${{ env.updater_name }} --configuration ${{ env.build_config }} -r ${{ matrix.RID }} --no-self-contained -o ${{ env.application_name }}/${{ matrix.name }}
      # zip {application_name}/{os_name} into a zip file where the root folder has name {application_name}
      - name: zip ${{ matrix.name }} build
        uses: papeloto/action-zip@v1
        with:
          files: ${{ env.application_name }}/${{ matrix.name }}
          dest: Releases/${{ env.application_name }}-${{ matrix.name }}.zip
          recursive: false

      - name: update release
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: add ${{ matrix.name }} to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          TAG_NAME: ${{ steps.tagName.outputs.tag }}
        with:
          upload_url: ${{ steps.update_release.outputs.upload_url }}
          asset_path: ./Releases/${{ env.application_name }}-${{ matrix.name }}.zip
          asset_identifier: ${{ env.application_name }}${{ matrix.asset_identifier }}.zip
          asset_content_type: application/zip